spring.application.name=api
spring.datasource.url=jdbc:postgresql://localhost:5432/healthhub
spring.datasource.username=schulzdimitri
spring.datasource.password=password

api.security.token.secret=${JWT_SECRET:defaultSecretKey}
